default:
  image: maven:3-jdk-11

stages:
  - build
  - test

compile-backend:
  stage: build

  artifacts:
    expire_in: "1 day"
    paths:
      - "backend/backend/target/backend.jar"
      - "backend/runner/target/backend.jar"

  # Cache maven deps
  cache:
    key: "backend_cache"
    paths:
      - backend/.repository/
  # Tell maven to use the cache
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.repository"

  script:
    - apt update
    - apt install make
    - make backend
  tags:
    - keep

compile-frontend:
  image: velcom-frontend:latest

  artifacts:
    expire_in: "1 day"
    paths:
      - "frontend/dist"

  # cache node modules
  cache:
    key: "frontend_cache"
    paths:
    - frontend/node_modules/

  stage: build
  script:
    - apk update
    - apk add make
    - make frontend
  tags:
    - keep

deploy:
  environment: "Keep"
  script:
    - docs/deploy.sh
  dependencies:
    - "compile-backend"
    - "compile-frontend"
  tags:
    - keep
